title: Modernize The Docs 

theme: uswds-jekyll

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: _pages
    values:
      layout: page

github:
  organization: opencontrol
  repository: fedramp-ssp
  default_branch: master

google_analytics_ua: UA-141012673-1
